# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

before_cache: Rscript -e 'remotes::install_cran("pkgdown")'

deploy:
  provider: script
  script: Rscript -e 'pkgdown::deploy_site_github()'
  skip_cleanup: true
  on:
    branch: v0-dev

jobs:
  include:
    - r: 3.2
    - r: oldrel
    - r: release
    - r: devel
    - os: osx

matrix:
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: change
