# R for travis: see documentation at https://docs.travis-ci.com/user/languages/r

language: R
sudo: false
cache: packages

r_github_packages:
  - r-lib/callr@v3.3.2

jobs:
  include:
    - r: 3.2
    - r: oldrel
    - r: release
      before_deploy:
        Rscript -e 'remotes::install_github("nteetor/pkgdown@master-nt-yonder")'
      deploy:
        provider: script
        script: Rscript -e 'pkgdown::deploy_site_github()'
        skip_cleanup: true
        on:
          branch: master
    - r: devel
    - os: osx

matrix:
  fast_finish: true

notifications:
  email:
    on_success: change
    on_failure: change
